### ISSUE TITLE
AXA Mansard's logo update

### ISSUE THREAD

**Issue by mrekemini** [PaystackHQ/nigerialogos#126]
Dear team, here is the new AXA Mansard brand logo. This is in compliance with AXA global brand principle. 

![AXA LOGO](https://user-images.githubusercontent.com/24295314/68962898-f353b800-07d5-11ea-8dd1-4e7c185a1447.jpg)

**Comment by aeadedoyin** [comment]
Hi, please do specify, what the differentiating factors are, cause it appears the logo stated looks just the same as the current, asides the wordmark on the side of the current logo.

**Comment by aeadedoyin** [comment]
Hi, Quick reminder.
