### ISSUE TITLE
9mobile Logo Update

### ISSUE THREAD

**Issue by chenemechete** [PaystackHQ/nigerialogos#128]
[9mobile Logo.svg.zip](https://github.com/PaystackHQ/nigerialogos/files/3896561/9mobile.Logo.svg.zip)

I turned the three strokes into shapes so when the logo is reduced or enlarged it looks proportional.

**Comment by aeadedoyin** [comment]
It appears that the current "9mobile Logo" is highly scalable and is fully optimized. 
Except you have numbers to back the reason you stated, hence create a PR and include these numbers and optional pictorial representation.

Thanks.

**Comment by chenemechete** [comment]
Hi Adedoyin,

Kindly view the scalability issue spotted in the SVG logo and what I
corrected.

[image: image.png]
