### ISSUE TITLE
Lagos State University Logo

### ISSUE THREAD

**Issue by AdejumoSamson** [PaystackHQ/nigerialogos#129]
Lagos State University Logo

![lasu](https://user-images.githubusercontent.com/16696126/72378895-995a6a80-3712-11ea-8819-79b11672e85d.png)

**Comment by ichtrojan** [comment]
Hi @AdejumoSamson 

You can get this Logo in this project by following the Guidelines [here](https://github.com/PaystackHQ/nigerialogos/blob/master/contributing.md)

Regards
Trojan
