### ISSUE TITLE
Sales Ruby, Learn Factory, Amplify, Allianz logo

### ISSUE THREAD

**Issue by siccoo** [PaystackHQ/nigerialogos#133]
Four folders created in the logo tree

**Comment by demilad** [comment]
Hi @siccoo 

You can get logo's into this project by following the Guidelines [here](https://github.com/PaystackHQ/nigerialogos/blob/master/contributing.md)

**Comment by siccoo** [comment]
I'm having a challenge contributing to the project. When I git push origin siccoo, it says this as shown in the image.
![stackoverflow](https://user-images.githubusercontent.com/43604282/75241968-78803d00-57c7-11ea-8c8b-8c60645e921e.PNG)
