### ISSUE TITLE
[Feature Request] API endpoint for "NigeriaLogos"

### ISSUE THREAD

**Issue by BolajiOlajide** [PaystackHQ/nigerialogos#159]
Hello @demilad and team,

I'm working on a project and I'm looking to make use of `nigerialogos`, however, I was hoping if there's a roadmap for having an API endpoint that could serve the URLs for the logos for a company.

Accessing the URL `https://nigerialogos.com/logos.json` gives me all the list of companies whose logos have been added but I am unable to access the URL from this endpoint, also looking to see if it's possible to have an endpoint to retrieve information for a single company.

I'm able to raise a PR for this, I just wanted to know if this is something the team is looking to support before I do that, or build out a solution separately.

Thank you.

<img width="914" alt="Screenshot 2021-02-15 at 03 08 43" src="https://user-images.githubusercontent.com/25608335/107898083-1e7a0980-6f3b-11eb-8ac6-e11a058d6c1c.png">

**Comment by demilad** [comment]
Hey @BolajiOlajide 
We currently don’t have an endpoint for URL's alone. We only have 
List view: `https://nigerialogos.com/logos.json` and 
Image view: `https://nigerialogos.com/logos/paystack/paystack.svg` endpoints right now

Feel free to make the PR 👍🏽

**Comment by BolajiOlajide** [comment]
Thank you for your response @demilad.

I just figured I can make up the URL for companies using the `file_name` field in the `logos.json` file.

**Comment by demilad** [comment]
Great @BolajiOlajide 
Share a link to the project when complete if you can. Would love to see how you’re using it
