### ISSUE TITLE
Searchbar Looks Weird On Some Screens

### ISSUE THREAD

**Issue by skaex** [PaystackHQ/nigerialogos#31]
On devices with smaller viewport heights the search bar begin to shrink into itself.

Like so:
![nglogos](https://user-images.githubusercontent.com/9969952/52662448-8472c700-2f04-11e9-99aa-c7840cb5c924.jpeg)

**Comment by fathermerry** [comment]
@skaex Fixed in https://github.com/PaystackHQ/nigerialogos/pull/44
