### ISSUE TITLE
Add Other Categories

### ISSUE THREAD

**Issue by AdoraNwodo** [PaystackHQ/nigerialogos#33]
There are other sectors that businesses exist in the country. e.g. Medicine, Law, Entertainment, Communications, Advertising etc.

I have two suggestions:

- One would be to add more categories to the list existing on the site.
- Another would be to wait till developers in these sectors want to add their logos and find out they are not listed so they add the categories themselves.

Which do you think works better?

**Comment by onyekvchi** [comment]
Hey @AdoraNwodo ! thanks a lot for contributing. Right now, we're going with the second approach. When anyone adds a logo and finds out the category isn't listed yet, they can add that as well.

**Comment by AdoraNwodo** [comment]
> Hey @AdoraNwodo ! thanks a lot for contributing. Right now, we're going with the second approach. When anyone adds a logo and finds out the category isn't listed yet, they can add that as well.
> 
> Let me know if this addresses your concerns so I can close this issue.
> 
> Thanks!

It does. 👍
