### ISSUE TITLE
setup instruction not so detailed

### ISSUE THREAD

**Issue by BigUncleYemi** [PaystackHQ/nigerialogos#46]
The Instruction on the ReadME.MD to set up the project locally isn't detailed enough. As after downloading the dependencies and starting up the SCSS, what else :man_shrugging:?

**Comment by fathermerry** [comment]
@BigUncleYemi Working on this now.

**Comment by fathermerry** [comment]
Fixed in https://github.com/PaystackHQ/nigerialogos/pull/49
