### ISSUE TITLE
Alphabetical Sorting

### ISSUE THREAD

**Issue by fathermerry** [PaystackHQ/nigerialogos#67]
As we approach 100 logos, It's getting harder to browse through the site. With alphabetical sorting, we can have a more efficient arrangement and make it easier to browse through the entire collection.

**Comment by dbkonxepts** [comment]
Sweet!

**Comment by dbkonxepts** [comment]
Quick Peep! 
Gonna do a PR soon.

// Desktop
![image](https://user-images.githubusercontent.com/20503883/54064481-f93fd500-4214-11e9-8b12-c98ccf0c61c1.png)

// Mobile
![image](https://user-images.githubusercontent.com/20503883/54064514-4fad1380-4215-11e9-8b9c-9c8ca7c302c3.png)

**Comment by fathermerry** [comment]
Nice idea with the quick jump but I think we can improve the design pattern. Can you make it vertical instead? An example of this is the contact list on most mobile operating systems

--
Cheers,
Opemipo Aikomo
